#!/usr/bin/env bash
#
# THIS SCRIPT HAS BEEN FULLY AI GENERATED BY GEMINI TO QUERY ALL THE
# IDS FOR CILOGON BROKER FLOW INTO new_imports.tf
#

set -euo pipefail

# ------------------------------------------------------------------------------
# Environment Checks & Configuration
# ------------------------------------------------------------------------------
KEYCLOAK_URL="${KEYCLOAK_URL:-https://keycloak.example.com}"
TARGET_REALM="${KEYCLOAK_REALM:-moc}"
ADMIN_REALM="${KEYCLOAK_ADMIN_REALM:-master}"
FLOW_ALIAS="CILogon First Broker Login"
IMPORTS_FILE="new_imports.tf"

if [[ -z "${TF_VAR_KEYCLOAK_USER_NAME:-}" || -z "${TF_VAR_KEYCLOAK_PASSWORD:-}" ]]; then
  echo "Error: TF_VAR_KEYCLOAK_USER_NAME and TF_VAR_KEYCLOAK_PASSWORD must be set." >&2
  exit 1
fi

if ! command -v jq &> /dev/null; then
  echo "Error: 'jq' command line tool is required." >&2
  exit 1
fi

# ------------------------------------------------------------------------------
# 1. Authenticate via admin-cli & get Access Token
# ------------------------------------------------------------------------------
echo "==> Authenticating with Keycloak ($KEYCLOAK_URL) as $TF_VAR_KEYCLOAK_USER_NAME..."

TOKEN_RESPONSE=$(curl -s -f -X POST "${KEYCLOAK_URL}/realms/${ADMIN_REALM}/protocol/openid-connect/token" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "grant_type=password" \
  -d "client_id=admin-cli" \
  -d "username=${TF_VAR_KEYCLOAK_USER_NAME}" \
  -d "password=${TF_VAR_KEYCLOAK_PASSWORD}")

ACCESS_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.access_token')

if [[ -z "$ACCESS_TOKEN" || "$ACCESS_TOKEN" == "null" ]]; then
  echo "Error: Failed to obtain access token." >&2
  exit 1
fi

# ------------------------------------------------------------------------------
# 2. Fetch Top-Level Flow GUID (Fixes top-level 404 error)
# ------------------------------------------------------------------------------
echo "==> Fetching top-level flow GUID for: '$FLOW_ALIAS'..."

FLOWS_JSON=$(curl -s -f -H "Authorization: Bearer $ACCESS_TOKEN" \
  -H "Accept: application/json" \
  "${KEYCLOAK_URL}/admin/realms/${TARGET_REALM}/authentication/flows")

FLOW_GUID=$(echo "$FLOWS_JSON" | jq -r --arg ALIAS "$FLOW_ALIAS" '.[] | select(.alias == $ALIAS) | .id')

if [[ -z "$FLOW_GUID" || "$FLOW_GUID" == "null" ]]; then
  echo "Error: Could not find flow with alias '$FLOW_ALIAS' in realm '$TARGET_REALM'." >&2
  exit 1
fi

echo "    Found parent flow GUID: $FLOW_GUID"

# ------------------------------------------------------------------------------
# 3. Query Flow Executions and Subflows
# ------------------------------------------------------------------------------
ENCODED_FLOW_ALIAS=$(python3 -c "import urllib.parse; print(urllib.parse.quote('''$FLOW_ALIAS'''))")

echo "==> Querying execution tree for flow: '$FLOW_ALIAS'..."

EXECUTIONS_JSON=$(curl -s -f -H "Authorization: Bearer $ACCESS_TOKEN" \
  -H "Accept: application/json" \
  "${KEYCLOAK_URL}/admin/realms/${TARGET_REALM}/authentication/flows/${ENCODED_FLOW_ALIAS}/executions")

# ------------------------------------------------------------------------------
# 4. Generate Corrected OpenTofu / Terraform Import Blocks (imports.tf)
# ------------------------------------------------------------------------------
echo "==> Writing corrected import blocks to '$IMPORTS_FILE'..."

# Header & Parent Flow Import
cat <<EOF > "$IMPORTS_FILE"
# ------------------------------------------------------------------------------
# Auto-generated OpenTofu / Terraform Import Blocks
# Flow: ${FLOW_ALIAS}
# Realm: ${TARGET_REALM}
# ------------------------------------------------------------------------------

# Top-Level Parent Flow
import {
  to = keycloak_authentication_flow.cilogon_first_broker_login
  id = "${TARGET_REALM}/${FLOW_GUID}"
}
EOF

# Subflows (using .flowId), Executions (using .id), and Execution Configs.
#
# The /executions endpoint returns a *depth-first* list of the flow tree. Each
# item carries a `level` (nesting depth; 0 == directly under the top-level
# flow). A nested item's parent is NOT the top-level flow but the most recent
# subflow seen one level up, so we walk the list carrying the alias of the last
# subflow at each level and use that as each item's parent_flow_alias in the
# import ID (id = "<realm>/<immediate-parent-alias>/<guid>"). Using the
# top-level alias for everything -- as an earlier version did -- flattens the
# tree and makes `-generate-config-out` emit an incorrect structure.
echo "$EXECUTIONS_JSON" | jq -r --arg REALM "$TARGET_REALM" --arg FLOW "$FLOW_ALIAS" '
  def sanitize: ascii_downcase | gsub("[^a-z0-9_]"; "_") | gsub("_+"; "_") | sub("^_"; "") | sub("_$"; "");

  reduce (to_entries[]) as $e (
    { parents: { "0": $FLOW }, out: [] };
    ($e.key) as $idx
    | ($e.value) as $item
    | ($item.level // 0) as $lvl
    | (.parents[($lvl | tostring)] // $FLOW) as $parent
    | if ($item.authenticationFlow // false) then
        ($item.displayName // $item.alias // "subflow" | sanitize) as $name
        # Record this subflow as the parent for items one level deeper.
        | .parents[(($lvl + 1) | tostring)] = $item.alias
        | .out += [
            "\n# Subflow: \($item.displayName // $item.alias)  (parent: \($parent))" +
            "\nimport {\n  to = keycloak_authentication_subflow.\($name)_\($idx)" +
            "\n  id = \"\($REALM)/\($parent)/\($item.flowId)\"\n}"
          ]
      else
        ($item.authenticator // "execution" | sanitize) as $name
        | .out += [
            "\n# Execution: \($item.authenticator // "step")  (parent: \($parent))" +
            "\nimport {\n  to = keycloak_authentication_execution.\($name)_\($idx)" +
            "\n  id = \"\($REALM)/\($parent)/\($item.id)\"\n}" +
            (
              if $item.executionConfig then
                "\n\n# Execution Config for \($item.authenticator // "step")" +
                "\nimport {\n  to = keycloak_authentication_execution_config.config_\($idx)" +
                "\n  id = \"\($REALM)/\($item.executionConfig)\"\n}"
              else
                ""
              end
            )
          ]
      end
  ) | .out[]
' >> "$IMPORTS_FILE"

echo "==> Done! Re-run OpenTofu using:"
echo "    tofu plan -generate-config-out=generated_auth_flow.tf"
